// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7QKXqzzlI_ySXENhWSLyKEF0fXV4co4Y',
    appId: '1:151063020623:web:8443a49b0cb95d93a5963a',
    messagingSenderId: '151063020623',
    projectId: 'flowey-tracking',
    authDomain: 'flowey-tracking.firebaseapp.com',
    storageBucket: 'flowey-tracking.firebasestorage.app',
    measurementId: 'G-FCLGP2CSH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXsYak_hSTcWyGoEWQ2MlglXnAn3fF-iI',
    appId: '1:151063020623:android:b3d35af6bef5bc1aa5963a',
    messagingSenderId: '151063020623',
    projectId: 'flowey-tracking',
    storageBucket: 'flowey-tracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbEfuNXmWnVYeJ0QMzw1j__uJtO5y47qk',
    appId: '1:151063020623:ios:20d2dc6e22469958a5963a',
    messagingSenderId: '151063020623',
    projectId: 'flowey-tracking',
    storageBucket: 'flowey-tracking.firebasestorage.app',
    iosBundleId: 'com.example.floweryDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbEfuNXmWnVYeJ0QMzw1j__uJtO5y47qk',
    appId: '1:151063020623:ios:20d2dc6e22469958a5963a',
    messagingSenderId: '151063020623',
    projectId: 'flowey-tracking',
    storageBucket: 'flowey-tracking.firebasestorage.app',
    iosBundleId: 'com.example.floweryDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7QKXqzzlI_ySXENhWSLyKEF0fXV4co4Y',
    appId: '1:151063020623:web:dbca710349c99b7ba5963a',
    messagingSenderId: '151063020623',
    projectId: 'flowey-tracking',
    authDomain: 'flowey-tracking.firebaseapp.com',
    storageBucket: 'flowey-tracking.firebasestorage.app',
    measurementId: 'G-9HCEXX7LQC',
  );
}
