class ApiConstants {
  static const String baseUrl = "https://flower.elevateegy.com/";
  static const String login = "api/v1/auth/signin";
  static const String signUp = "api/v1/auth/signup";
  static const String forgotPassword = "api/v1/auth/forgotPassword";
  static const String verifyResetCode = "api/v1/auth/verifyResetCode";
  static const String getHomeData = "api/v1/home";
  static const String productDetails = "api/v1/products";
  static const String getAllCategories = "api/v1/categories";
  static const String getBestSellerProducts = "api/v1/best-seller";
  static const String getAllOccasions = "api/v1/occasions";
  static const String getAllProducts = "api/v1/products";
  static const resetPassword = '/api/v1/auth/resetPassword';
  static const String changePassword = "api/v1/auth/change-password";
  static const String getLoggedUserInfo = "api/v1/auth/profile-data";
  static const String editProfile = "api/v1/auth/editProfile";
  static const String uploadPhoto = "api/v1/auth/upload-photo";
  static const String cart = 'api/v1/cart';
  static const String occasions = "api/v1/occasions";
  static const String getBestSeller = "api/v1/best-seller";
  static const String getAllCategoriesEndpoint = "api/v1/categories";
  static const String logout = "api/v1/auth/logout";
  static const String order = "api/v1/orders";
  static const String addAddress = "api/v1/addresses";
  static const String getLoggedUserAddresses = "api/v1/addresses";
  static const String deleteAddress = "api/v1/addresses";
  static const String products = "api/v1/products";
  static const String quantityInDescending = "api/v1/products";
//  static const String products = "api/v1/products";
// static const String products = "api/v1/products";
  static const String getAllNotifications = "api/v1/notifications";
  static const String cash = "api/v1/orders";
  static const String creditCard =
      "api/v1/orders/checkout?url=http://localhost:3000";
}
